#!/usr/bin/env python3
"""
Job narration workflow for live-stream job search demos.

Input:
  A JSON response from the job search backend.

Output:
  1. A short live narration script generated by a Doubao text model.
  2. An audio file generated by Doubao TTS.

The module is intentionally workflow-friendly:
  - Core functions can be imported by queue workers.
  - CLI can read from a file or stdin.
  - Provider settings come from env vars and CLI args.
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import subprocess
import sys
import uuid
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, Optional


DEFAULT_LLM_BASE_URL = "https://ark.cn-beijing.volces.com/api/v3"
DEFAULT_TTS_HTTP_URL = "https://openspeech.bytedance.com/api/v3/tts/unidirectional"
LOCAL_TEST_DOUBAO_API_KEY = ""
LOCAL_TEST_TTS_API_KEY = ""
DEFAULT_LLM_MODEL = "doubao-1-5-lite-32k-250115"
DEFAULT_TTS_APP_ID = "1830992029"
DEFAULT_TTS_RESOURCE_ID = "volc.service_type.10029"
DEFAULT_TTS_VOICE = "zh_female_wanqudashu_moon_bigtts"
DEFAULT_TTS_FORMAT = "mp3"
DEFAULT_SAMPLE_RATE = 24000
TEMPLATE_TARGET_MAX_CHARS = 115


class WorkflowError(RuntimeError):
    """Raised when a recoverable workflow step fails."""


def load_project_env() -> None:
    """Load simple KEY=VALUE entries from the project-root .env if present."""
    env_path = Path(__file__).resolve().parent.parent / ".env"
    if not env_path.exists():
        return
    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip("'\"")
        if key and value and key not in os.environ:
            os.environ[key] = value


load_project_env()


@dataclass
class JobPayload:
    id: Optional[Any]
    name: str
    company_name: str
    city: str
    company_type_key: str
    company_title_key: str
    start_time: str
    end_time: str
    recommended_message: str
    extra_fields: Dict[str, Any]
    raw: Dict[str, Any]


@dataclass
class NarrationResult:
    spoken_text: str
    duration_level: str = "short"
    should_play: bool = True
    title: str = ""
    tags: Optional[list[str]] = None
    risk_tips: Optional[list[str]] = None
    source: str = "llm"


@dataclass
class DoubaoLLMConfig:
    api_key: str
    model: str
    base_url: str = DEFAULT_LLM_BASE_URL
    temperature: float = 0.25
    max_tokens: int = 500


@dataclass
class DoubaoTTSConfig:
    api_key: str
    app_id: str = DEFAULT_TTS_APP_ID
    http_url: str = DEFAULT_TTS_HTTP_URL
    resource_id: str = DEFAULT_TTS_RESOURCE_ID
    voice: str = DEFAULT_TTS_VOICE
    audio_format: str = DEFAULT_TTS_FORMAT
    sample_rate: int = DEFAULT_SAMPLE_RATE


def load_json_source(source: str) -> Dict[str, Any]:
    """Load JSON from a file path or stdin when source is '-'."""
    if source == "-":
        content = sys.stdin.read()
    else:
        content = Path(source).read_text(encoding="utf-8")
    try:
        return json.loads(content)
    except json.JSONDecodeError as exc:
        raise WorkflowError(f"Input is not valid JSON: {exc}") from exc


def pick_first_job(response_json: Dict[str, Any]) -> Dict[str, Any]:
    """Pick data[0] from the backend response."""
    data = response_json.get("data")
    if not isinstance(data, list) or not data:
        raise WorkflowError("No job found: response.data is empty or not a list.")
    first = data[0]
    if not isinstance(first, dict):
        raise WorkflowError("Invalid job item: response.data[0] is not an object.")
    return first


def _clean_text(value: Any, default: str = "") -> str:
    if value is None:
        return default
    text = str(value).strip()
    return " ".join(text.split())


def normalize_job(job: Dict[str, Any]) -> JobPayload:
    """Extract fields that are useful for narration and keep raw data for traceability."""
    extra_field_names = [
        "salary",
        "salary_desc",
        "salary_range",
        "experience",
        "work_experience",
        "education",
        "degree",
        "welfare",
        "benefits",
        "job_description",
        "description",
        "content",
        "address",
        "district",
        "recruit_num",
        "job_type",
        "tags",
        "skill_tags",
        "position",
        "related_majors",
        "job_require_major",
        "publish_time",
    ]
    extra_fields = {
        key: job[key]
        for key in extra_field_names
        if key in job and job[key] not in (None, "", [], {})
    }
    return JobPayload(
        id=job.get("id"),
        name=_clean_text(job.get("name"), "岗位信息"),
        company_name=_clean_text(job.get("company_name"), "公司信息暂未展示"),
        city=_clean_text(job.get("city"), "城市暂未展示"),
        company_type_key=_clean_text(job.get("company_type_key")),
        company_title_key=_clean_text(job.get("company_title_key")),
        start_time=_clean_text(job.get("start_time")),
        end_time=_clean_text(job.get("end_time")),
        recommended_message=_clean_text(
            job.get("recommendedMessage") or job.get("recommended_message")
        ),
        extra_fields=extra_fields,
        raw=job,
    )


def build_llm_messages(job: JobPayload) -> list[dict[str, str]]:
    compact_job = {
        "id": job.id,
        "name": job.name,
        "company_name": job.company_name,
        "city": job.city,
        "company_type_key": job.company_type_key,
        "company_title_key": job.company_title_key,
        "start_time": job.start_time,
        "end_time": job.end_time,
        "recommendedMessage": job.recommended_message,
        "extra_fields": job.extra_fields,
    }
    system_prompt = """
你是直播间的求职查岗解说助手。你的任务是把一个真实打开的岗位信息，改写成适合直播间播报的中文短口播。

要求：
1. 只基于传入 JSON 中已有字段生成，不要编造薪资、学历、经验、福利、风险。
2. 口播自然、清晰、偏专业求职顾问风格。
3. 控制在 60 到 120 个中文字符之间，适合 8 到 15 秒播完。
4. 不要承诺岗位真实性、录用概率、一定高薪、一定靠谱。
5. 如果字段缺失，用“页面暂未展示”这类保守表达，不要猜。
6. 只输出口播文案本身，不要输出 JSON、Markdown、标题、标签、解释或前后缀。
""".strip()
    user_prompt = "请根据这个岗位 JSON 生成直播查岗口播：\n" + json.dumps(
        compact_job, ensure_ascii=False
    )
    return [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]


def generate_template_script(job: JobPayload) -> NarrationResult:
    """Local fallback for dry runs or provider outages."""
    text = generate_template_spoken_text(job)
    return build_narration_result(job, text, source="template")


def generate_template_spoken_text(job: JobPayload) -> str:
    """Render a 10-15 second narration from deterministic fact fragments."""
    opening = build_template_opening(job)
    candidates = [
        build_recommended_sentence(job),
        build_keyword_sentence(job),
        build_requirement_sentence(job),
        build_salary_sentence(job),
        build_company_sentence(job),
    ]
    closing = build_closing_sentence(job, has_details=any(candidates))
    return compose_template_text(opening, candidates, closing)


def compose_template_text(
    opening: str,
    candidates: Iterable[Optional[str]],
    closing: str,
    max_chars: int = TEMPLATE_TARGET_MAX_CHARS,
) -> str:
    parts = [opening]
    for sentence in candidates:
        if not sentence:
            continue
        candidate = "".join(parts + [sentence, closing])
        if len(candidate) <= max_chars:
            parts.append(sentence)
    parts.append(closing)
    return "".join(parts)


def build_template_opening(job: JobPayload) -> str:
    name = job.name
    company = job.company_name
    if is_displayed(job.city):
        return f"现在看到的是{job.city}的{name}，公司是{company}。"
    return f"现在看到的是{name}，公司是{company}。"


def build_recommended_sentence(job: JobPayload) -> Optional[str]:
    recommended = _strip_sentence_end(job.recommended_message)
    if not recommended:
        return None
    return f"推荐理由是{limit_fragment(recommended, 32)}。"


def build_keyword_sentence(job: JobPayload) -> Optional[str]:
    keywords = derive_template_keywords(job)
    if not keywords:
        return None
    return f"页面关键词包括{'、'.join(keywords)}。"


def derive_template_keywords(job: JobPayload, max_keywords: int = 3) -> list[str]:
    keywords: list[str] = []

    def add(value: Any) -> None:
        text = _clean_text(value).strip("\"'“”‘’")
        if text and text not in keywords:
            keywords.append(text)

    for key in ("tags", "skill_tags"):
        for item in iter_tag_values(job.extra_fields.get(key)):
            add(item)

    name = job.name
    if "实习" in name:
        add("实习")
    if "校招" in name or "秋招" in name or "春招" in name:
        add("校招")
    if "管培" in name:
        add("管培生")
    return keywords[:max_keywords]


def build_requirement_sentence(job: JobPayload) -> Optional[str]:
    bits = []
    education = first_extra_text(job, "education", "degree")
    experience = first_extra_text(job, "experience", "work_experience")
    job_type = first_extra_text(job, "job_type", "position")
    if education:
        bits.append(f"要求{education}")
    if experience:
        bits.append(f"经验要求{experience}")
    if job_type:
        bits.append(f"岗位类型是{job_type}")
    if not bits:
        return None
    return "，".join(bits[:3]) + "。"


def build_salary_sentence(job: JobPayload) -> Optional[str]:
    salary = first_extra_text(job, "salary", "salary_desc", "salary_range")
    if not salary:
        return None
    return f"薪资信息为{limit_fragment(salary, 22)}。"


def build_company_sentence(job: JobPayload) -> Optional[str]:
    bits = [bit for bit in [job.company_title_key, job.company_type_key] if bit]
    if not bits:
        return None
    return f"企业信息显示为{'、'.join(bits[:2])}。"


def build_closing_sentence(job: JobPayload, has_details: bool) -> str:
    job_type = first_extra_text(job, "job_type", "position")
    if any(word in f"{job.name}{job_type}" for word in ("实习", "校招", "秋招", "春招")):
        return "适合正在看校招或实习的同学重点留意。"
    if has_details:
        return "方向匹配的话，可以重点看一下详情。"
    return "页面信息有限，建议重点核对岗位职责和投递入口。"


def first_extra_text(job: JobPayload, *keys: str) -> str:
    for key in keys:
        value = job.extra_fields.get(key)
        if isinstance(value, list):
            joined = "、".join(_clean_text(item) for item in value if _clean_text(item))
            if joined:
                return joined
        else:
            text = _clean_text(value)
            if text:
                return text
    return ""


def is_displayed(value: str) -> bool:
    return bool(value) and "暂未展示" not in value


def limit_fragment(text: str, max_chars: int) -> str:
    text = _clean_text(text)
    if len(text) <= max_chars:
        return text
    return text[:max_chars].rstrip("，、；;。.!！?？") + "..."


def build_narration_result(job: JobPayload, spoken_text: str, source: str) -> NarrationResult:
    """Wrap generated speech text with deterministic metadata."""
    spoken_text = limit_spoken_text(clean_llm_spoken_text(spoken_text))
    return NarrationResult(
        spoken_text=spoken_text,
        duration_level="short",
        should_play=bool(spoken_text),
        title=job.name,
        tags=derive_job_tags(job),
        risk_tips=derive_risk_tips(job),
        source=source,
    )


def derive_job_tags(job: JobPayload, max_tags: int = 3) -> list[str]:
    """Derive short display tags without asking the model."""
    tags: list[str] = []

    def add(value: Any) -> None:
        text = _clean_text(value).strip("\"'“”‘’")
        if text and text not in tags:
            tags.append(text)

    for key in ("tags", "skill_tags", "job_type", "experience", "work_experience", "education", "degree"):
        for item in iter_tag_values(job.extra_fields.get(key)):
            add(item)

    name = job.name
    if "实习" in name:
        add("实习")
    if "校招" in name or "秋招" in name or "春招" in name:
        add("校招")
    if "管培" in name:
        add("管培生")
    if job.company_title_key:
        add(job.company_title_key)
    if job.company_type_key:
        add(job.company_type_key)

    return tags[:max_tags]


def iter_tag_values(value: Any) -> Iterable[Any]:
    if isinstance(value, list):
        return value
    if not isinstance(value, str):
        return []

    text = value.strip()
    if text.startswith("["):
        try:
            parsed = json.loads(text)
        except json.JSONDecodeError:
            parsed = None
        if isinstance(parsed, list):
            return parsed

    return [item for item in text.replace("，", ",").replace("、", ",").split(",") if item.strip()]


def derive_risk_tips(job: JobPayload, max_tips: int = 2) -> list[str]:
    """Generate conservative non-spoken tips for trace/debug consumers."""
    tips: list[str] = []

    def add(value: str) -> None:
        if value and value not in tips:
            tips.append(value)

    if not any(key in job.extra_fields for key in ("salary", "salary_desc", "salary_range")):
        add("页面暂未展示薪资")
    if not any(key in job.extra_fields for key in ("experience", "work_experience")):
        add("经验要求以页面为准")
    if not any(key in job.extra_fields for key in ("education", "degree")):
        add("学历要求以页面为准")
    if "招满即止" in job.end_time:
        add("岗位可能随时下架")

    return tips[:max_tips]


def clean_llm_spoken_text(text: str) -> str:
    """Normalize common wrappers when a model is asked for plain speech text."""
    text = _clean_text(text)
    if text.startswith("```"):
        text = text.strip("`").strip()
        for prefix in ("text", "plaintext", "markdown", "中文"):
            if text.lower().startswith(prefix):
                text = text[len(prefix):].strip()
                break
    for prefix in ("口播文案：", "口播文案:", "文案：", "文案:", "spoken_text：", "spoken_text:"):
        if text.startswith(prefix):
            text = text[len(prefix):].strip()
            break
    return text.strip().strip("\"'“”‘’")


def generate_script_with_doubao(job: JobPayload, config: DoubaoLLMConfig) -> NarrationResult:
    """Call a Doubao text model through Volcengine Ark OpenAI-compatible API."""
    try:
        from openai import OpenAI
    except ImportError as exc:
        raise WorkflowError("Missing dependency: run `pip install -r requirements.txt`.") from exc

    client = OpenAI(api_key=config.api_key, base_url=config.base_url)
    completion = client.chat.completions.create(
        model=config.model,
        messages=build_llm_messages(job),
        temperature=config.temperature,
        max_tokens=config.max_tokens,
    )
    content = completion.choices[0].message.content or ""
    narration = build_narration_result(job, content, source="doubao")
    if not narration.spoken_text:
        raise WorkflowError("Doubao LLM returned empty spoken_text.")
    return narration


def limit_spoken_text(text: str, max_chars: int = 140) -> str:
    """Keep generated narration short enough for a live stream."""
    text = _clean_text(text)
    if len(text) <= max_chars:
        return text
    clipped = text[:max_chars]
    for mark in ["。", "！", "？", "；", "，"]:
        idx = clipped.rfind(mark)
        if idx >= 60:
            return clipped[: idx + 1]
    return clipped.rstrip("，、；") + "。"


def _strip_sentence_end(text: str) -> str:
    return _clean_text(text).rstrip("。.!！?？；;，,、")


def synthesize_with_doubao_tts(text: str, output_path: Path, config: DoubaoTTSConfig) -> Path:
    """
    Generate speech through Doubao BigTTS / OpenSpeech V3 HTTP Chunked API.

    This matches the console page "语音合成大模型-字符版":
      https://openspeech.bytedance.com/api/v3/tts/unidirectional
    """
    try:
        import requests
    except ImportError as exc:
        raise WorkflowError("Missing dependency: run `pip install -r requirements.txt`.") from exc

    output_path.parent.mkdir(parents=True, exist_ok=True)
    headers = {
        "Content-Type": "application/json",
        "Connection": "keep-alive",
        "X-Api-App-Id": config.app_id,
        "X-Api-Access-Key": config.api_key,
        "X-Api-Resource-Id": config.resource_id,
        "X-Api-Request-Id": str(uuid.uuid4()),
    }
    payload = {
        "user": {"uid": "job_narration"},
        "req_params": {
            "text": text,
            "speaker": config.voice,
            "additions": json.dumps(
                {
                    "disable_markdown_filter": False,
                    "enable_language_detector": True,
                },
                ensure_ascii=False,
            ),
            "audio_params": {
                "format": config.audio_format,
                "sample_rate": config.sample_rate,
            },
        },
    }

    audio_chunks: list[bytes] = []
    try:
        with requests.post(
            config.http_url,
            headers=headers,
            json=payload,
            stream=True,
            timeout=(10, 60),
        ) as response:
            if response.status_code in (401, 403):
                raise WorkflowError(
                    f"Doubao TTS authentication failed with HTTP {response.status_code}. "
                    "请确认 X-Api-App-Id 是语音合成大模型字符版实例ID，"
                    "X-Api-Access-Key 是该服务可用的 API Key。"
                )
            response.raise_for_status()
            for line in response.iter_lines(decode_unicode=True):
                if not line:
                    continue
                line = line.strip()
                if line.startswith("data:"):
                    line = line[5:].strip()
                try:
                    event = json.loads(line)
                except json.JSONDecodeError as exc:
                    raise WorkflowError(f"Doubao TTS returned non-JSON chunk: {line}") from exc

                if event.get("data"):
                    audio_chunks.append(base64.b64decode(event["data"]))

                code = event.get("code")
                if code == 20000000:
                    break
                if isinstance(code, int) and code > 0:
                    raise WorkflowError(f"Doubao TTS error: {event}")
    except requests.RequestException as exc:
        raise WorkflowError(f"Doubao TTS request failed: {exc}") from exc

    if not audio_chunks:
        raise WorkflowError("Doubao TTS returned no audio chunks.")
    output_path.write_bytes(b"".join(audio_chunks))
    return output_path


def play_audio_file(path: Path) -> None:
    """Best-effort local playback on macOS."""
    afplay = Path("/usr/bin/afplay")
    if not afplay.exists():
        raise WorkflowError("Local playback only supports macOS afplay by default.")
    subprocess.run([str(afplay), str(path)], check=True)


def llm_config_from_env(args: argparse.Namespace) -> DoubaoLLMConfig:
    api_key = (
        args.llm_api_key
        or os.getenv("DOUBAO_LLM_API_KEY")
        or os.getenv("DOUBAO_API_KEY")
        or os.getenv("ARK_API_KEY")
        or LOCAL_TEST_DOUBAO_API_KEY
    )
    model = args.llm_model or os.getenv("DOUBAO_LLM_MODEL") or DEFAULT_LLM_MODEL
    if not api_key:
        raise WorkflowError("Missing Doubao LLM API key. Set DOUBAO_API_KEY, DOUBAO_LLM_API_KEY, or ARK_API_KEY.")
    if not model:
        raise WorkflowError("Missing Doubao LLM model/endpoint. Set DOUBAO_LLM_MODEL.")
    return DoubaoLLMConfig(
        api_key=api_key,
        model=model,
        base_url=args.llm_base_url or os.getenv("DOUBAO_LLM_BASE_URL") or DEFAULT_LLM_BASE_URL,
    )


def tts_config_from_env(args: argparse.Namespace) -> DoubaoTTSConfig:
    api_key = (
        args.tts_api_key
        or os.getenv("DOUBAO_TTS_API_KEY")
        or os.getenv("DOUBAO_API_KEY")
        or os.getenv("AI_GATEWAY_API_KEY")
        or LOCAL_TEST_TTS_API_KEY
    )
    if not api_key:
        raise WorkflowError("Missing Doubao TTS API key. Set DOUBAO_API_KEY, DOUBAO_TTS_API_KEY, or AI_GATEWAY_API_KEY.")
    return DoubaoTTSConfig(
        api_key=api_key,
        app_id=args.tts_app_id
        or os.getenv("DOUBAO_TTS_APP_ID")
        or os.getenv("VOLCENGINE_TTS_APPID")
        or DEFAULT_TTS_APP_ID,
        http_url=args.tts_http_url or os.getenv("DOUBAO_TTS_HTTP_URL") or DEFAULT_TTS_HTTP_URL,
        resource_id=args.tts_resource_id
        or os.getenv("DOUBAO_TTS_RESOURCE_ID")
        or DEFAULT_TTS_RESOURCE_ID,
        voice=args.tts_voice or os.getenv("DOUBAO_TTS_VOICE") or DEFAULT_TTS_VOICE,
        audio_format=args.tts_format or os.getenv("DOUBAO_TTS_FORMAT") or DEFAULT_TTS_FORMAT,
        sample_rate=int(args.tts_sample_rate or os.getenv("DOUBAO_TTS_SAMPLE_RATE") or DEFAULT_SAMPLE_RATE),
    )


def run_workflow(args: argparse.Namespace) -> dict[str, Any]:
    response_json = load_json_source(args.input)
    first_job = pick_first_job(response_json)
    job = normalize_job(first_job)

    if args.dry_run:
        narration = generate_template_script(job)
    else:
        narration = generate_script_with_doubao(job, llm_config_from_env(args))

    audio_path = None
    if narration.should_play and not args.script_only and not args.dry_run:
        output_path = Path(args.output)
        audio_path = synthesize_with_doubao_tts(
            narration.spoken_text,
            output_path,
            tts_config_from_env(args),
        )
        if args.play:
            play_audio_file(audio_path)

    result = {
        "job": asdict(job) | {"raw": job.raw},
        "narration": asdict(narration),
        "audio_path": str(audio_path) if audio_path else None,
    }
    return result


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate Doubao narration audio from the first job in backend JSON."
    )
    parser.add_argument("-i", "--input", default="-", help="Input JSON file path, or '-' for stdin.")
    parser.add_argument(
        "-o",
        "--output",
        default="output/job_narration.mp3",
        help="Output audio path.",
    )
    parser.add_argument("--dry-run", action="store_true", help="No API calls; use local template only.")
    parser.add_argument("--script-only", action="store_true", help="Generate text only; skip TTS.")
    parser.add_argument("--play", action="store_true", help="Play generated audio with afplay on macOS.")

    parser.add_argument("--llm-api-key", default="", help="Override DOUBAO_API_KEY or DOUBAO_LLM_API_KEY.")
    parser.add_argument("--llm-base-url", default="", help="Override DOUBAO_LLM_BASE_URL.")
    parser.add_argument("--llm-model", default="", help="Override DOUBAO_LLM_MODEL.")

    parser.add_argument("--tts-api-key", default="", help="Override DOUBAO_API_KEY or DOUBAO_TTS_API_KEY.")
    parser.add_argument("--tts-app-id", default="", help="Override DOUBAO_TTS_APP_ID.")
    parser.add_argument("--tts-http-url", default="", help="Override DOUBAO_TTS_HTTP_URL.")
    parser.add_argument("--tts-voice", default="", help="Override DOUBAO_TTS_VOICE.")
    parser.add_argument("--tts-format", default="", help="Override DOUBAO_TTS_FORMAT.")
    parser.add_argument("--tts-sample-rate", default="", help="Override DOUBAO_TTS_SAMPLE_RATE.")
    parser.add_argument("--tts-resource-id", default="", help="Override DOUBAO_TTS_RESOURCE_ID.")
    return parser


def main(argv: Optional[Iterable[str]] = None) -> int:
    parser = build_arg_parser()
    args = parser.parse_args(argv)
    try:
        result = run_workflow(args)
    except WorkflowError as exc:
        print(json.dumps({"ok": False, "error": str(exc)}, ensure_ascii=False), file=sys.stderr)
        return 2
    print(json.dumps({"ok": True, **result}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
